# Base Image for executing jobs - contains Java and Android SDK with some additional libraries
# See https://github.com/jangrewe/gitlab-ci-android
image: jangrewe/gitlab-ci-android

# Build Stages - release and deploy not used currently
stages:
  - prerequisites
  - build
  - buildTest
  - deviceTests
  - test
  - docs

# Define Gradle Home to use it for (optional) caching
before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

# Cache instruction - will save intermediate results for later jobs
# Might actually not speed up your pipeline runtime - just check it for yourself
cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/


prepare_build:
  stage: prerequisites
  tags:
    - testlab
  script:
    - mkdir apks
  artifacts:
    paths:
      - apks/

# Build a debug apk
assembleDebug:
  stage: build
  tags:
    - testlab
  script:
    - ./gradlew assembleDebug
    - mv app/build/outputs/apk/debug/app-debug.apk apks/app-debug.apk
  artifacts:
    paths:
      - apks/app-debug.apk

# Build a debug test apk
assembleDebugTest:
  stage: buildTest
  tags:
    - testlab
  script:
    - ./gradlew assembleDebugAndroidTest
    - mv app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk apks/app-debug-androidTest.apk
  artifacts:
    paths:
      - apks/app-debug-androidTest.apk

run_device_tests:
  stage: deviceTests
  tags:
    - testlab
  script:
    - cd apks
    - ls

## Generate Docs via Dokka
generateDocs:
  stage: docs
  tags:
    - testlab
  script:
    - ./gradlew dokkaHtmlMultiModule
  artifacts:
    paths:
      - build/dokkaMultiModuleOutput/**
